### ISSUE TITLE
Table 3: what is the voxel size of CenterPoint + CenterPoint(VoxelNet)?

### ISSUE THREAD

**Issue by chaytonmin** [georghess/voxel-mae#15]
In Table 5, voxel grid shape (x,y,z)  is (200,200,1). Is this setting also for CenterPoint + CenterPoint(VoxelNet) in Table 3?

**Comment by georghess** [comment]
Hi, for Centerpoint we use the [default settings](https://github.com/open-mmlab/mmdetection3d/blob/main/configs/_base_/models/centerpoint_voxel01_second_secfpn_nus.py), i.e. voxel size [0.1, 0.1, 0.2] with grid size [-50, -50, -5, 50, 50, 3].
