### ISSUE TITLE
How to get the reconstruction visualization result?

### ISSUE THREAD

**Issue by hollow-503** [georghess/voxel-mae#6]
Hello, thanks for your really great job! I have a question about the visualization of reconstrustion: How to get the reconstruction result like figure 3 in your paper? Have you released the code?
![image](https://user-images.githubusercontent.com/57223231/210030450-adf3a501-1fe7-4d66-8710-cf7dc1019c0f.png)

**Comment by georghess** [comment]
Hello,
Unfortuantely I cannot share the visualization code.
